name: Deploy to cdk
on:
  repository_dispatch:
    types: [deploy_infra]

jobs:
  clone_yearn_simulations:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout Main Repo
        uses: actions/checkout@v2
        with:
          path: main
      - name: Checkout Yearn Simulations Repo
        uses: actions/checkout@v2
        with:
          repository: yearn/yearn-simulations
          ref: ${{ github.event.client_payload.SHA }}
          path: yearn_simulations
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}-${{ hashFiles('**/requirements-dev.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install Infra Python Requirements
        working-directory: main
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
      - name: Install Python packages
        run: |
          pip install -r yearn_simulations/requirements.txt
          pip install eth-brownie>=1.17.0
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install -g aws-cdk
      - name: cdk deploy
        working-directory: ${{ github.workspace }}/main
        run: |
          cdk deploy --all --require-approval never
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'us-east-1'
          YEARN_SIMULATIONS_WORKSPACE: '${{ github.workspace }}/yearn_simulations'
          CDK_DEPLOY_REGION: 'us-east-1'
          CDK_DEPLOY_VPC: 'vpc-45b3f922'
          CDK_DEPLOY_ACCOUNT: '377926405243'
