name: Deploy to cdk
on:
  repository_dispatch:
    types: [deploy_infra]

jobs:
  clone_yearn_simulations:
    runs-on: ubuntu-latest
    environment: Numan-Local
    steps:
      - name: Checkout Yearn Simulations Repo
        uses: actions/checkout@v2
        with:
          repository: yearn/yearn-simulations
          ref: ${{ github.event.client_payload.SHA }}
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install Packages
        uses: BSFishy/pip-action@v1
        with:
          packages: |
            eth-brownie>=1.17.0
          requirements: requirements-dev.txt
      - name: Install Packages
        uses: BSFishy/pip-action@v1
        with:
          requirements: ${{ env.GITHUB_WORKSPACE }}requirements.txt
      - name: cdk deploy
        uses: youyo/aws-cdk-github-actions@v2
        with:
          cdk_subcommand: 'deploy'
          cdk_stack: '*'
          cdk_args: '--require-approval never'
          actions_comment: false
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'us-east-1'